name: Trigger Netlify Build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7,10,13,15 * * 1-5'
jobs:
  build:
    name: Netlify build
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} $BUILD_HOOK
        env:
          BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
